[project]
name = "pdf-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "weasyprint>=65.1",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
]
